### ISSUE TITLE
kiwiclientd : AssertionError

### ISSUE THREAD

**Issue by UgoPoddine** [jks-prv/kiwiclient#125]
Hello,

i'm trying to use kiwiclientd to pipe KiwiSDR data flow over Loopback interface.
Kiwiclient installation it's at its last release and I'm working on PREEMPT_RT Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux.
I'm not using pulseaudio.
Kiwiclient runs perfectly when generating IQ or demodulated files.
If I try, for example : 

 python3 kiwiclientd.py -h

the result is :

Traceback (most recent call last):
  File "/home/ugo/kiwiclient/kiwiclientd.py", line 16, in <module>
    import soundcard as sc
  File "/usr/local/lib/python3.9/dist-packages/soundcard/__init__.py", line 4, in <module>
    from soundcard.pulseaudio import *
  File "/usr/local/lib/python3.9/dist-packages/soundcard/pulseaudio.py", line 265, in <module>
    _pulse = _PulseAudio()
  File "/usr/local/lib/python3.9/dist-packages/soundcard/pulseaudio.py", line 76, in __init__
    assert self._pa_context_get_state(self.context)==_pa.PA_CONTEXT_READY
AssertionError

Python soundcard is NOT installed at user level and via PIP.

Any help will be appreciated
Best regard

Ugo

**Comment by rikvanriel** [comment]
You need to install the Python soundcard library on your system.

You can do that either through apt-get, if Debian has a package, or through pip.
